"""change length in role

Revision ID: 0694c9ade970
Revises: b2b3beefcc91
Create Date: 2026-01-09 15:00:00.973616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0694c9ade970'
down_revision: Union[str, Sequence[str], None] = 'b2b3beefcc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('contracttype', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('schedule_unique_key'), 'schedule', type_='unique')
    op.alter_column('status', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('worktype', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worktype', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('team', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('status', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_unique_constraint(op.f('schedule_unique_key'), 'schedule', ['document', 'start_date_pe', 'start_time_pe'], postgresql_nulls_not_distinct=False)
    op.alter_column('role', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('contracttype', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('campaign', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
