"""add reason and status adherence

Revision ID: 0a40d7fea788
Revises: f6c9694dff29
Create Date: 2026-01-18 16:41:18.699256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a40d7fea788'
down_revision: Union[str, Sequence[str], None] = 'f6c9694dff29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('main_deviation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('attendance', sa.Column('adherence_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'adherence_status')
    op.drop_column('attendance', 'main_deviation_reason')
    # ### end Alembic commands ###
