"""add Optional in main_deviation_reason

Revision ID: 1aeeff1c56ea
Revises: 0a40d7fea788
Create Date: 2026-01-18 16:46:49.007181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aeeff1c56ea'
down_revision: Union[str, Sequence[str], None] = '0a40d7fea788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'main_deviation_reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'main_deviation_reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
