"""delete relation attendance-worker

Revision ID: 209ef7a9e29b
Revises: 7233cdd3c45b
Create Date: 2026-01-14 23:42:56.213606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209ef7a9e29b'
down_revision: Union[str, Sequence[str], None] = '7233cdd3c45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_api_email_fkey'), 'attendance', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('attendance_api_email_fkey'), 'attendance', 'worker', ['api_email'], ['api_email'])
    # ### end Alembic commands ###
