"""change attendance tabla and key

Revision ID: 2dc5733898c7
Revises: 7e6d0430d6c0
Create Date: 2026-01-11 14:21:40.523893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc5733898c7'
down_revision: Union[str, Sequence[str], None] = '7e6d0430d6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('time_aux_productive', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('time_aux_non_productive', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('adherence', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('time_outside_scheduled', sa.Integer(), nullable=True))
    op.create_unique_constraint('attendance_unique_key', 'attendance', ['api_email', 'date'])
    op.drop_column('attendance', 'offline_minutes')
    op.drop_column('attendance', 'out_of_adherence')
    op.create_unique_constraint('workers_unique_key', 'worker', ['document'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workers_unique_key', 'worker', type_='unique')
    op.add_column('attendance', sa.Column('out_of_adherence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('offline_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('attendance_unique_key', 'attendance', type_='unique')
    op.drop_column('attendance', 'time_outside_scheduled')
    op.drop_column('attendance', 'adherence')
    op.drop_column('attendance', 'time_aux_non_productive')
    op.drop_column('attendance', 'time_aux_productive')
    # ### end Alembic commands ###
