"""change attendance table delete on cascade from schedules

Revision ID: 35016f381818
Revises: 519d036a19af
Create Date: 2026-01-15 21:43:42.472146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35016f381818'
down_revision: Union[str, Sequence[str], None] = '519d036a19af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_schedule_id'), table_name='attendance')
    op.drop_constraint(op.f('attendance_schedule_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_schedule_id_fkey'), 'attendance', 'schedule', ['schedule_id'], ['id'])
    op.create_index(op.f('ix_attendance_schedule_id'), 'attendance', ['schedule_id'], unique=False)
    # ### end Alembic commands ###
