"""add late_login in attendance

Revision ID: 519d036a19af
Revises: e35b8337d084
Create Date: 2026-01-15 08:33:44.859308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519d036a19af'
down_revision: Union[str, Sequence[str], None] = 'e35b8337d084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('late_login', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('late_login_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'late_login_minutes')
    op.drop_column('attendance', 'late_login')
    # ### end Alembic commands ###
