"""add contact reason, contact received and tht high

Revision ID: 6cf0f0d2bdb6
Revises: 82c5249b763c
Create Date: 2026-02-08 14:20:28.154660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cf0f0d2bdb6'
down_revision: Union[str, Sequence[str], None] = '82c5249b763c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactsreceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_pe', sa.Date(), nullable=True),
    sa.Column('interval_pe', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date_es', sa.Date(), nullable=True),
    sa.Column('interval_es', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('contacts_received', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team', 'date_pe', 'interval_pe', 'date_es', 'interval_es', name='uq_contacts_received')
    )
    op.create_table('contactsreason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacts_received_id', sa.Integer(), nullable=False),
    sa.Column('contact_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacts_received_id'], ['contactsreceived.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contacts_received_id', 'contact_reason', name='uq_contacts_reason')
    )
    op.create_table('ththighbyagent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacts_received_id', sa.Integer(), nullable=False),
    sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacts_received_id'], ['contactsreceived.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contacts_received_id', 'api_email', name='uq_tht_high')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ththighbyagent')
    op.drop_table('contactsreason')
    op.drop_table('contactsreceived')
    # ### end Alembic commands ###
