"""add unique key in schedule

Revision ID: 7e6d0430d6c0
Revises: ef4d187927b1
Create Date: 2026-01-10 17:45:59.754580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6d0430d6c0'
down_revision: Union[str, Sequence[str], None] = 'ef4d187927b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('schedule_unique_key', 'schedule', ['document', 'start_date_pe', 'start_time_pe', 'end_time_pe'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_unique_key', 'schedule', type_='unique')
    # ### end Alembic commands ###
