"""add effective_work_time in attendance

Revision ID: 7eba5a6f0817
Revises: 1aeeff1c56ea
Create Date: 2026-01-18 18:39:31.306925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eba5a6f0817'
down_revision: Union[str, Sequence[str], None] = '1aeeff1c56ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('effective_work_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'effective_work_time')
    # ### end Alembic commands ###
