"""change attendance table

Revision ID: 8f1978f44200
Revises: 2dc5733898c7
Create Date: 2026-01-14 17:48:05.394747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1978f44200'
down_revision: Union[str, Sequence[str], None] = '2dc5733898c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('schedule_id', sa.Integer(), nullable=False))
    op.add_column('attendance', sa.Column('time_aux_no_productive', sa.Integer(), nullable=False))
    op.add_column('attendance', sa.Column('early_login', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('early_login_minutes', sa.Integer(), nullable=False))
    op.add_column('attendance', sa.Column('late_logout', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('late_logout_minutes', sa.Integer(), nullable=False))
    op.add_column('attendance', sa.Column('left_early', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('early_leave_minutes', sa.Integer(), nullable=False))
    op.alter_column('attendance', 'time_aux_productive',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'adherence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('attendance_unique_key'), 'attendance', type_='unique')
    op.create_unique_constraint('attendance_schedule_unique', 'attendance', ['api_email', 'schedule_id'])
    op.create_index(op.f('ix_attendance_api_email'), 'attendance', ['api_email'], unique=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_schedule_id'), 'attendance', ['schedule_id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'schedule', ['schedule_id'], ['id'])
    op.drop_column('attendance', 'time_outside_scheduled')
    op.drop_column('attendance', 'time_aux_non_productive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('time_aux_non_productive', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('time_outside_scheduled', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_schedule_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_api_email'), table_name='attendance')
    op.drop_constraint('attendance_schedule_unique', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('attendance_unique_key'), 'attendance', ['api_email', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance', 'adherence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('attendance', 'time_aux_productive',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('attendance', 'early_leave_minutes')
    op.drop_column('attendance', 'left_early')
    op.drop_column('attendance', 'late_logout_minutes')
    op.drop_column('attendance', 'late_logout')
    op.drop_column('attendance', 'early_login_minutes')
    op.drop_column('attendance', 'early_login')
    op.drop_column('attendance', 'time_aux_no_productive')
    op.drop_column('attendance', 'schedule_id')
    # ### end Alembic commands ###
