"""init alembic schemas

Revision ID: 96fd8018fac7
Revises: 
Create Date: 2025-12-04 00:47:08.973141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96fd8018fac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contracttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worktype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('supervisor', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('coordinator', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('work_type_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('contract_type_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('api_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('api_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('observation_1', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('observation_2', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('trainee', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('productive', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contracttype.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['worktype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_email'),
    sa.UniqueConstraint('document')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('out_of_adherence', sa.Integer(), nullable=True),
    sa.Column('offline_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_email'], ['worker.api_email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_document', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('obs', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.ForeignKeyConstraint(['worker_document'], ['worker.document'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('attendance')
    op.drop_table('worker')
    op.drop_table('worktype')
    op.drop_table('team')
    op.drop_table('status')
    op.drop_table('role')
    op.drop_table('contracttype')
    op.drop_table('campaign')
    # ### end Alembic commands ###
