"""change is_rest_day Optional

Revision ID: ef4d187927b1
Revises: e9551c0f4bd1
Create Date: 2026-01-10 17:40:10.677470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4d187927b1'
down_revision: Union[str, Sequence[str], None] = 'e9551c0f4bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'is_rest_day',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('schedule_unique_key'), 'schedule', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('schedule_unique_key'), 'schedule', ['document', 'start_date_pe', 'start_time_pe', 'end_time_pe'], postgresql_nulls_not_distinct=False)
    op.alter_column('schedule', 'is_rest_day',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
