"""change lasy raise

Revision ID: f6c9694dff29
Revises: 35016f381818
Create Date: 2026-01-18 12:57:45.973484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c9694dff29'
down_revision: Union[str, Sequence[str], None] = '35016f381818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('schedule_worker_document_fkey'), 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'worker', ['document'], ['document'], ondelete='CASCADE')
    op.alter_column('worker', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'work_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'contract_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('worker_status_id_fkey'), 'worker', type_='foreignkey')
    op.drop_constraint(op.f('worker_work_type_id_fkey'), 'worker', type_='foreignkey')
    op.drop_constraint(op.f('worker_role_id_fkey'), 'worker', type_='foreignkey')
    op.drop_constraint(op.f('worker_contract_type_id_fkey'), 'worker', type_='foreignkey')
    op.drop_constraint(op.f('worker_campaign_id_fkey'), 'worker', type_='foreignkey')
    op.drop_constraint(op.f('worker_team_id_fkey'), 'worker', type_='foreignkey')
    op.create_foreign_key(None, 'worker', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'worker', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'worker', 'worktype', ['work_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'worker', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'worker', 'status', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'worker', 'contracttype', ['contract_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.create_foreign_key(op.f('worker_team_id_fkey'), 'worker', 'team', ['team_id'], ['id'])
    op.create_foreign_key(op.f('worker_campaign_id_fkey'), 'worker', 'campaign', ['campaign_id'], ['id'])
    op.create_foreign_key(op.f('worker_contract_type_id_fkey'), 'worker', 'contracttype', ['contract_type_id'], ['id'])
    op.create_foreign_key(op.f('worker_role_id_fkey'), 'worker', 'role', ['role_id'], ['id'])
    op.create_foreign_key(op.f('worker_work_type_id_fkey'), 'worker', 'worktype', ['work_type_id'], ['id'])
    op.create_foreign_key(op.f('worker_status_id_fkey'), 'worker', 'status', ['status_id'], ['id'])
    op.alter_column('worker', 'contract_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'work_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_worker_document_fkey'), 'schedule', 'worker', ['document'], ['document'])
    # ### end Alembic commands ###
