"""add sla_breached_table in db

Revision ID: fe5ecd02314b
Revises: f56d5eda8072
Create Date: 2026-01-26 11:11:26.514072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe5ecd02314b'
down_revision: Union[str, Sequence[str], None] = 'f56d5eda8072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slabreached',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_es', sa.Date(), nullable=True),
    sa.Column('interval_es', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date_pe', sa.Date(), nullable=True),
    sa.Column('interval_pe', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chat_breached', sa.Integer(), nullable=True),
    sa.Column('link', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team', 'date_es', 'interval_es', 'api_email', name='uq_sla_breached_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slabreached')
    # ### end Alembic commands ###
